### ISSUE TITLE
How to port the acc algorithm on stm32 platform

### ISSUE THREAD

**Issue by masterchen** [uStepper/uStepper#13]
Tahnks for this good project,can you give some suggestions on How to port the acc algorithm on stm32 platform

**Comment by uStepperOld** [comment]
Hi masterchen,

The algorithm is implemented in assembly, due to the limited computing power of the 8bit AVR MCU

Because of this you will need to rewrite the code to have it run on the stm32 platform

If i was to do the port, i would write it in plain C instead of assembly, due to the much greater computational power of the stm32 platform. I would recommend you to use fixed point math, instead of floating point in order to maximize performance. Unless of course you have an FPU available

You can use the documentation of the algorithm mentioned in the top comments of the uStepper.S source file as a reference. This gives a great explanation of how the algorithm works

Unfortunately I'm can't give you more assistance, as we don't have the resources assist with custom coding like this

Best regards
Thomas

**Comment by masterchen** [comment]
Hi uStepper，
Thank you very much for your kindly help!
